<%@ Page Title="" Language="C#" MasterPageFile="~/PublicWeb/user.Master" AutoEventWireup="true" CodeBehind="niaGoals.aspx.cs" Inherits="niaps_ver_1._0.PublicWeb.niaGoals" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link href="../Content/style.css" rel="stylesheet" />
    <table class="table"><tbody><tr><td>NIA Goals</td><td>
        &nbsp;</td></tr><tr><td>&nbsp;• To protect, promote and advance the common interest of insurers in Nigeria • To advise members on any action or proposed action by Government or any other authority in connection with any legislation or policy. • To advise or consult with the Government regarding any act or thing done or being contemplated by it or its agencies or other statutory bodies with regards to any matter relating to Insurance business. • To guide and assist members in complying with laws, regulations, orders and Government directives relating generally to the business of insurance. • To create better understanding of insurance by all sections of the community including the furtherance of knowledge and research on Insurance and related matters. • To collect, collate and disseminate statistical, economic and other information relating to Insurance • To maintain constant dialogue with other trade associations in the Insurance industry with a view to fostering good relationships between 
            them and the NIA as well as the insuring public • To confer, consult, maintain contact and co-operate with individuals, associations, societies, institutions or bodies within or outside Nigeria having objectives similar to those of the Association • To promote personal and friendly relationship among members of the Association. Strategies to achieving our Goals: • Regular meetings of the specialized committees of the Association every month where issues affecting the industry are addressed. • Maintenance of a well-equipped research and statistics department. • Organizing conferences, seminars and training courses for employees of member companies and interested public. • Maintaining highly skilled manpower conversant with modern information and communication technology. • Interacting passively with the media and other intersected groups • Interacting passively with the media and other interested groups • Interacting with supervisory authority and the entire membership of the 
            Association • Publication of technical journals, statistical digests, newsletters and business environment watch. </td><td>
                &nbsp;</td></tr></tbody></table>
</asp:Content>
