//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetRecord
    {
        public assetRecord()
        {
            this.assetUpdateHistories = new HashSet<assetUpdateHistory>();
        }
    
        public string assetId { get; set; }
        public string name { get; set; }
        public System.DateTime datePurchased { get; set; }
        public string receivingDept { get; set; }
        public decimal cost { get; set; }
        public string remark { get; set; }
        public string insurance { get; set; }
        public string policyNumber { get; set; }
        public decimal sumInsured { get; set; }
        public System.DateTime coverDate { get; set; }
        public System.DateTime expirydate { get; set; }
        public string status { get; set; }
        public string vendor { get; set; }
        public string premium { get; set; }
    
        public virtual ICollection<assetUpdateHistory> assetUpdateHistories { get; set; }
    }
}
