//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentStaffRecord
    {
        public int Id { get; set; }
        public string staffId { get; set; }
        public string designation { get; set; }
        public string department { get; set; }
        public string qualification { get; set; }
        public Nullable<System.DateTime> date_Joined { get; set; }
        public string degree { get; set; }
        public Nullable<int> probationPeriod { get; set; }
        public Nullable<System.DateTime> dateOfConfirmation { get; set; }
    
        public virtual staffRecord staffRecord { get; set; }
    }
}
