//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicator
    {
        public string IndicatorId { get; set; }
        public string quarter { get; set; }
        public string year { get; set; }
    }
}
