//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave
    {
        public int leaveId { get; set; }
        public string staffId { get; set; }
        public string name { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string comment { get; set; }
        public Nullable<int> leaveDaysGranted { get; set; }
        public Nullable<int> totalUnusedLeaveDays { get; set; }
    
        public virtual staffRecord staffRecord { get; set; }
    }
}
