//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int newsId { get; set; }
        public string newsBy { get; set; }
        public string message { get; set; }
        public string postebBy { get; set; }
        public System.DateTime date { get; set; }
    }
}
