//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualification
    {
        public int qualificationId { get; set; }
        public string staffId { get; set; }
        public string name { get; set; }
        public System.DateTime dateObtained { get; set; }
        public string institution { get; set; }
        public string typeOfQualification { get; set; }
    
        public virtual staffRecord staffRecord { get; set; }
    }
}
