//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class query
    {
        public int Id { get; set; }
        public string staffId { get; set; }
        public string natureOfQuery { get; set; }
        public string status { get; set; }
        public System.DateTime dateIssued { get; set; }
        public Nullable<System.DateTime> dateReplied { get; set; }
        public string reply { get; set; }
        public string actionTaken { get; set; }
        public string issuedBy { get; set; }
        public Nullable<System.DateTime> disciplinaryEffectDate { get; set; }
        public Nullable<int> index { get; set; }
    }
}
