//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffReview
    {
        public int reviewId { get; set; }
        public string staffId { get; set; }
        public string training_workShop { get; set; }
        public Nullable<System.DateTime> dateObtained { get; set; }
        public string deatailedScheduleDuties { get; set; }
        public string comments { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual staffRecord staffRecord { get; set; }
    }
}
