//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace niaps_ver_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffRecord
    {
        public staffRecord()
        {
            this.answerToQuestions = new HashSet<answerToQuestion>();
            this.currentStaffRecords = new HashSet<currentStaffRecord>();
            this.employmentRecords = new HashSet<employmentRecord>();
            this.issuedQueries = new HashSet<issuedQuery>();
            this.leaves = new HashSet<leave>();
            this.pendingLeaves = new HashSet<pendingLeave>();
            this.qualifications = new HashSet<qualification>();
            this.staffNextOfKins = new HashSet<staffNextOfKin>();
            this.staffUpdateHistories = new HashSet<staffUpdateHistory>();
            this.staffReviews = new HashSet<staffReview>();
            this.users = new HashSet<user>();
        }
    
        public string staffId { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string address { get; set; }
        public string Lga { get; set; }
        public string state { get; set; }
        public string passport { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string marritalStatus { get; set; }
        public string formOfIdentification { get; set; }
        public string middleName { get; set; }
        public int age { get; set; }
        public string status { get; set; }
        public string idNumber { get; set; }
    
        public virtual ICollection<answerToQuestion> answerToQuestions { get; set; }
        public virtual ICollection<currentStaffRecord> currentStaffRecords { get; set; }
        public virtual ICollection<employmentRecord> employmentRecords { get; set; }
        public virtual ICollection<issuedQuery> issuedQueries { get; set; }
        public virtual ICollection<leave> leaves { get; set; }
        public virtual ICollection<pendingLeave> pendingLeaves { get; set; }
        public virtual ICollection<qualification> qualifications { get; set; }
        public virtual ICollection<staffNextOfKin> staffNextOfKins { get; set; }
        public virtual ICollection<staffUpdateHistory> staffUpdateHistories { get; set; }
        public virtual ICollection<staffReview> staffReviews { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
